controller_joint_names: ['', 'rightwheel', 'leftwheel', 'rightbackcaster', 'rightbackcasterwheel', 'leftbackcaster', 'leftbackcasterwheel', 'rightfrontcaster', 'rightfrontcasterwheel', 'leftfrontcaster', 'leftfrontcasterwheel', ]
